config/routes.rb
Rails.application.routes.draw do
  resources :group_interviews

  resources :coffee_chats

  resources :interviews

  devise_for :users
  resources :users
  resources :rush_applications

  devise_scope :user do
    authenticated :user do
      root :to => 'rush_applications#edit', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end


end

app/controllers/interviews_controller.rb
class InterviewsController < ApplicationController
  before_action :set_interview, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_filter do 
    redirect_to authenticated_root_path unless current_user && current_user.admin?
  end

  # GET /interviews
  # GET /interviews.json
  def index
    @apps = Application.order(:name).all
  end
  
  # GET /interviews/new
  def new
    @interview = Interview.new
    @user_list = []
    Application.all.each do |app|
      if app.submitted and !app.user.is_admin? and !app.user.is_brother?
        @user_list << [app.name,app.id]
      end
    end
  end

  # POST /interviews
  # POST /interviews.json
  def create
    @interview = Interview.new(interview_params)

    if @interview.save
      flash[:notice] = 'Successfully submitted form.'
      redirect_to authenticated_root_path
    else
      flash[:failure] = 'Failed to submit form.'
      redirect_to authenticated_root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_interview
      @interview = Interview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def interview_params
      params.require(:interview).permit(:application_id,:interviewer_1,:interviewer_2,:interviewer_3,:gpa, :score_1 , :question_1, :score_2 , :question_2 , :score_3 , :question_3 , :score_4 , :question_4 , :score_5 , :question_5 , :score_6 , :question_6 , :overall , :question_7 , :question_8 , :comments)
    end
end

app/helpers/interviews_helper.rb
module InterviewsHelper
end

app/views/interviews/_form.html.haml
.container
  %h2 Interview Form
%br
.container
  = simple_form_for(@interview, :html => { id: "interview_form" }) do |f|
    = f.error_notification
    %b Candidate:
    = f.select :application_id, @user_list, {}, {:class => "form-control"}
    %br
    = f.input :interviewer_1, label: "Interviewer's Last Name #1", required: true
    = f.input :interviewer_2, label: "Interviewer's Last Name #2", required: true
    = f.input :interviewer_3, label: "Interviewer's Last Name #3"
    = f.input :gpa, label: "Candidate's GPA", required: true
    %br
    = f.label :score_1, "* What are three highlights from your resume? Please keep your answers brief."
    %table{:class => "table radio_table text-center"}
      %tr
        %td
          Not Accomplished
        %td
          = f.input :score_1, label: false, as: :radio_buttons, collection: [ 1,2,3,4,5,6,7 ], item_wrapper_class: 'radio-inline', required: true
        %td
          Highly Accomplished
      %tr
    = f.input :question_1, label:false, required: true
    %br
    = f.label :score_2, "* Why do you want to join SEP and what are you looking to gain?"
    %table{:class => "table radio_table text-center"}
      %tr
        %td
          Poor Expectations
        %td
          = f.input :score_2, label: false, as: :radio_buttons, collection: [ 1,2,3,4,5,6,7 ], item_wrapper_class: 'radio-inline', required: true
        %td
          Aspirational Expectations
      %tr
    = f.input :question_2, label:false, required: true
    %br
    = f.label :score_3, "* Tell me a skill or idea you have taught yourself in the last six months. How did you go about teaching yourself this new skill or idea, and what was the result?"
    %table{:class => "table radio_table text-center"}
      %tr
        %td
          Not Curious & Motivated
        %td
          = f.input :score_3, label: false, as: :radio_buttons, collection: [ 1,2,3,4,5,6,7 ], item_wrapper_class: 'radio-inline', required: true
        %td
          Highly Curious & Motivated
      %tr
    = f.input :question_3, label:false, required: true
    %br
    = f.label :score_4, "* What is the ideal business you would like to be apart of or start? Follow up: Now tell me 3 more in different industries (not specific startups we're looking for industries of interest)."
    %table{:class => "table radio_table text-center"}
      %tr
        %td
          Not Knowledgeable
        %td
          = f.input :score_4, label: false, as: :radio_buttons, collection: [ 1,2,3,4,5,6,7 ], item_wrapper_class: 'radio-inline', required: true
        %td
          Highly Knowledgeable
      %tr
    = f.input :question_4, label:false, required: true
    %br
    = f.label :score_5, "* Tell me about a startup you find interesting and why? follow-up with: can you think of any concerns with this product/startup?"
    %table{:class => "table radio_table text-center"}
      %tr
        %td
          Poor Critical Thinking
        %td
          = f.input :score_5, label: false, as: :radio_buttons, collection: [ 1,2,3,4,5,6,7 ], item_wrapper_class: 'radio-inline', required: true
        %td
          Advanced Critical Thinking
      %tr
    = f.input :question_5, label:false, required: true
    %br
    = f.label :score_6, "* Market sizing questions, these could include, find the number of red cups used in 1 day at Berkeley or the number of people in USA who enjoy electronic music?"
    %table{:class => "table radio_table text-center"}
      %tr
        %td
          Poor Structure and Analysis
        %td
          = f.input :score_6, label: false, as: :radio_buttons, collection: [ 1,2,3,4,5,6,7 ], item_wrapper_class: 'radio-inline', required: true
        %td
          Advanced Structure and Analysis
      %tr
    = f.input :question_6, label:false, required: true
    %br
    = f.label :overall, "* Overall Candidate Rating"
    %table{:class => "table radio_table text-center"}
      %tr
        %td
          Terrible Candidate
        %td
          = f.input :overall, label: false, as: :radio_buttons, collection: [ 1,2,3,4,5,6,7 ], item_wrapper_class: 'radio-inline', required: true
        %td
          Amazing Candidate
      %tr
    %br
    = f.input :question_7, label: "What do you know about the pledge process so far?", required: true
    = f.input :question_8, label: "Do you have any questions for us?", required: true
    = f.input :comments, label: "Intangible Additions to Interview", required: true
    = f.button :submit, "Submit"
:javascript
  $("#interview_form").validate();

app/views/interviews/_interview.html.haml
%table{:class => "table"}
  %tr
    %td 
      %p
        %b Interviewer 1
    %td 
      %p= interview.interviewer_1
  %tr
    %td 
      %p
        %b Interviewer 2
    %td 
      %p= interview.interviewer_2
  %tr
    %td 
      %p
        %b Interviewer 3
    %td 
      %p= interview.interviewer_3
  %tr
    %td 
      %p
        %b GPA
    %td 
      %p= interview.gpa
  %tr
    %td 
      %p
        %b What are three highlights from your resume? 
    %td 
      %p= "Score: " + interview.score_1.to_s
      %p= interview.question_1
  %tr
    %td 
      %p
        %b Why do you want to join SEP and what are you looking to gain?
    %td 
      %p= "Score: " + interview.score_2.to_s
      %p= interview.question_2
  %tr
    %td 
      %p
        %b Tell me a skill or idea you have taught yourself in the last six months. How did you go about teaching yourself this new skill or idea, and what was the result? 
    %td 
      %p= "Score: " + interview.score_3.to_s
      %p= interview.question_3
  %tr
    %td 
      %p
        %b What is the ideal business you would like to be apart of or start? Follow up: Now tell me 3 more in different industries (not specific startups we're looking for industries of interest). 
    %td 
      %p= "Score: " + interview.score_4.to_s
      %p= interview.question_4
  %tr
    %td 
      %p
        %b Tell me about a startup you find interesting and why? follow-up with: can you think of any concerns with this product/startup?
    %td 
      %p= "Score: " + interview.score_5.to_s
      %p= interview.question_5
  %tr
    %td 
      %p
        %b Market sizing questions, these could include, find the number of red cups used in 1 day at Berkeley or the number of people in USA who enjoy electronic music? 
    %td 
      %p= "Score: " + interview.score_6.to_s
      %p= interview.question_6
  %tr
    %td 
      %p
        %b Overall Score
    %td 
      %p= interview.overall
  %tr
    %td 
      %p
        %b What do you know about the pledge process so far?
    %td 
      %p= interview.question_7
  %tr
    %td 
      %p
        %b Do you have any questions for us?
    %td 
      %p= interview.question_8
  %tr
    %td 
      %p
        %b Intangible Additions to Interview
    %td 
      %p= interview.comments


      

      

app/views/interviews/edit.html.haml
%h1 Editing interview

= render 'form'

= link_to 'Show', @interview
\|
= link_to 'Back', interviews_path

app/views/interviews/index.html.haml
.container
  %h1 Listing interviews
%br
.container
  .table-responsive
    %table{:class => "table"}
      %tr
        %th Candidate
        %th Interviewer 1
        %th Interviewer 2
        %th Interviewer 3
        %th GPA
        %th What are three highlights from your resume? 
        %th Why do you want to join SEP and what are you looking to gain?
        %th Tell me a skill or idea you have taught yourself in the last six months. How did you go about teaching yourself this new skill or idea, and what was the result? 
        %th What is the ideal business you would like to be apart of or start? Follow up: Now tell me 3 more in different industries (not specific startups we're looking for industries of interest).
        %th Tell me about a startup you find interesting and why? follow-up with: can you think of any concerns with this product/startup?
        %th Market sizing questions, these could include, find the number of red cups used in 1 day at Berkeley or the number of people in USA who enjoy electronic music? 
        %th Overall Score
        %th What do you know about the pledge process so far?
        %th Do you have any questions for us?
        %th Intangible Additions to Interview
      - @apps.each do |app|
        - app.interviews.each do |interview|
          %tr
            %td
              %p= app.name
            %td
              %p= interview.interviewer_1
            %td
              %p= interview.interviewer_2
            %td
              %p= interview.interviewer_3
            %td
              %p= interview.gpa
            %td
              %p= "Score: " + interview.score_1.to_s
              %p= interview.question_1
            %td
              %p= "Score: " + interview.score_2.to_s
              %p= interview.question_2
            %td
              %p= "Score: " + interview.score_3.to_s
              %p= interview.question_3
            %td
              %p= "Score: " + interview.score_4.to_s
              %p= interview.question_4
            %td
              %p= "Score: " + interview.score_5.to_s
              %p= interview.question_5
            %td
              %p= "Score: " + interview.score_6.to_s
              %p= interview.question_6
            %td
              %p= interview.overall
            %td
              %p= interview.question_7
            %td
              %p= interview.question_8
            %td
              %p= interview.comments

app/views/interviews/new.html.haml
= render 'form'