config/routes.rb
Rails.application.routes.draw do
  resources :group_interviews

  resources :coffee_chats

  resources :interviews

  devise_for :users
  resources :users
  resources :rush_applications

  devise_scope :user do
    authenticated :user do
      root :to => 'rush_applications#edit', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end


end

app/controllers/group_interviews_controller.rb
class GroupInterviewsController < ApplicationController
  before_action :set_group_interview, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_filter do 
    redirect_to authenticated_root_path unless current_user && current_user.admin?
  end

  # GET /group_interviews
  # GET /group_interviews.json
  def index
    @apps = Application.order(:name).all
  end
  
  # GET /group_interviews/new
  def new
    @group_interview = GroupInterview.new
    @user_list = []
    Application.all.each do |app|
      if app.submitted and !app.user.is_admin? and !app.user.is_brother?
        @user_list << [app.name,app.id]
      end
    end
  end

  # POST /group_interviews
  # POST /group_interviews.json
  def create
    @group_interview = GroupInterview.new(group_interview_params)

    
    if @group_interview.save
      flash[:notice] = 'Successfully submitted form.'
      redirect_to authenticated_root_path
    else
      flash[:failure] = 'Failed to submit form.'
      redirect_to authenticated_root_path
    end
        
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group_interview
      @group_interview = GroupInterview.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_interview_params
      params.require(:group_interview).permit(:author,:score,:comments,:application_id)
    end
end

app/helpers/group_interviews_helper.rb
module GroupInterviewsHelper
end

app/views/group_interviews/_form.html.haml
.container
  %h2 Group Interview Form
%br
.container
  = simple_form_for(@group_interview, :html => { id: "group_interview_form"}) do |f|
    = f.error_notification
    %b Interviewee:
    = f.select :application_id, @user_list, {}, {:class => "form-control"}
    %br
    = f.input :author, :label => "Your name", required: true
    = f.input :score, required: true
    = f.input :comments, required: true
    = f.button :submit, "Submit"
:javascript
  $("#group_interview_form").validate();

app/views/group_interviews/_group_interview.html.haml
%td
  %p=group_interview.author
%td
  %p=group_interview.score
%td
  %p=group_interview.comments

app/views/group_interviews/edit.html.haml
%h1 Editing group_interview

= render 'form'

= link_to 'Show', @group_interview
\|
= link_to 'Back', group_interviews_path

app/views/group_interviews/index.html.haml
.container
  %h1 Group Interviews
%br
.container
  .table-responsive
    %table{:class => "table"}
      %tr
        %th Rushee
        %th Brother
        %th Score
        %th Comments
        - @apps.each do |app|
          -app.group_interviews.each do |gp|
            %tr
              %td= app.name
              = render gp  

app/views/group_interviews/new.html.haml
= render 'form'