config/routes.rb
Rails.application.routes.draw do
  resources :group_interviews

  resources :coffee_chats

  resources :interviews

  devise_for :users
  resources :users
  resources :rush_applications

  devise_scope :user do
    authenticated :user do
      root :to => 'rush_applications#edit', as: :authenticated_root
    end
    unauthenticated :user do
      root :to => 'devise/sessions#new', as: :unauthenticated_root
    end
  end


end

app/models/coffee_chat.rb
class CoffeeChat < ActiveRecord::Base
  belongs_to :application
end

app/controllers/coffee_chats_controller.rb
class CoffeeChatsController < ApplicationController
  before_action :set_coffee_chat, only: [:show, :edit, :update, :destroy]
  before_filter :authenticate_user!
  before_filter do 
    redirect_to authenticated_root_path unless current_user && current_user.admin?
  end

  # GET /coffee_chats
  # GET /coffee_chats.json
  def index
    @apps = Application.order(:name).all
  end

  # GET /coffee_chats/new
  def new
    @coffee_chat = CoffeeChat.new
    @user_list = []
    Application.all.each do |app|
      if app.submitted and !app.user.is_admin? and !app.user.is_brother?
        @user_list << [app.name,app.id]
      end
    end
  end

  # POST /coffee_chats
  # POST /coffee_chats.json
  def create
    @coffee_chat = CoffeeChat.new(coffee_chat_params)

    if @coffee_chat.save
      flash[:notice] = 'Successfully submitted form.'
      redirect_to authenticated_root_path
    else
      flash[:failure] = 'Failed to submit form.'
      redirect_to authenticated_root_path
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_coffee_chat
      @coffee_chat = CoffeeChat.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def coffee_chat_params
      params.require(:coffee_chat).permit(:application_id,:interviewer_1,:interviewer_2,:overall,:empathy,:grit,:curiosity,:analytical,:comments)
    end
end

app/helpers/coffee_chats_helper.rb
module CoffeeChatsHelper
end

app/views/coffee_chats/_coffee_chat.html.haml
%table{:class => "table"}
  %tr
    %td 
      %p
        %b Interviewer 1
    %td
      %p=coffee_chat.interviewer_1
  %tr
    %td 
      %p
        %b Interviewer 2
    %td
      %p=coffee_chat.interviewer_2
  %tr
    %td 
      %p
        %b Overall Score
    %td
      %p=coffee_chat.overall
  %tr
    %td 
      %p
        %b Empathy Score
    %td
      %p=coffee_chat.empathy
  %tr
    %td 
      %p
        %b Grit Score
    %td
      %p=coffee_chat.grit
  %tr
    %td 
      %p
        %b Curiosity Score
    %td
      %p=coffee_chat.curiosity
  %tr
    %td 
      %p
        %b Analytical Score
    %td
      %p=coffee_chat.analytical
  %tr
    %td 
      %p
        %b Comments
    %td
      %p=coffee_chat.comments

app/views/coffee_chats/_form.html.haml
.container
  %h2 Coffee Chat Form
%br
.container
  = simple_form_for(@coffee_chat, :html => { id: "coffee_chat_form" }) do |f|
    = f.error_notification

    %b Interviewee:
    = f.select :application_id, @user_list, {}, {:class => "form-control"}
    %br
    = f.input :interviewer_1, required: true
    = f.input :interviewer_2, required: true
    = f.input :overall, :label => "Overall Score", required: true
    = f.input :empathy, :label => "Empathy Score", required: true
    = f.input :grit, :label => "Grit Score", required: true
    = f.input :curiosity, :label => "Curiosity Score", required: true
    = f.input :analytical, :label => "Analytical Score", required: true
    = f.input :comments, required: true
    = f.button :submit, "Submit"
:javascript
  $("#coffee_chat_form").validate();

app/views/coffee_chats/edit.html.haml
%h1 Editing coffee_chat

= render 'form'

= link_to 'Show', @coffee_chat
\|
= link_to 'Back', coffee_chats_path

app/views/coffee_chats/index.html.haml
.container
  %h1 Coffee Chats
%br
.container
  .table-responsive
    %table{:class => "table"}
      %tr
        %th Rushee
        %th Interviewer 1
        %th Interviewer 2
        %th Overall Score
        %th Empathy Score
        %th Grit Score
        %th Curiosity Score
        %th Analytical Score
        %th Comments
      - @apps.each do |app|
        - app.coffee_chats.each do |coffee_chat|
          %tr
            %td= app.name
            %td= coffee_chat.interviewer_1
            %td= coffee_chat.interviewer_2
            %td= coffee_chat.overall
            %td= coffee_chat.empathy
            %td= coffee_chat.grit
            %td= coffee_chat.curiosity
            %td= coffee_chat.analytical
            %td= coffee_chat.comments

app/views/coffee_chats/new.html.haml
= render 'form'